# Generated by Django 2.2.12 on 2022-05-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(default=1, verbose_name='货物ID')),
                ('to_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('text', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存在')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名')),
                ('img', models.CharField(default='', max_length=50, verbose_name='图片')),
                ('kinds', models.CharField(default='', max_length=50, verbose_name='种类')),
                ('discribe', models.TextField(default='', max_length=100, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='价格')),
                ('from_id', models.IntegerField(default=1, verbose_name='商家ID')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存在')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='SellGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField(default=1, verbose_name='货物ID')),
                ('from_id', models.IntegerField(default=1, verbose_name='商家ID')),
                ('to_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good_num', models.IntegerField(default=1, verbose_name='下单数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存在')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('passWord', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('eMail', models.CharField(default='', max_length=50, verbose_name='邮件')),
                ('location', models.CharField(default='', max_length=50, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存在')),
                ('isSeller', models.BooleanField(default=False, verbose_name='是否为商家')),
            ],
        ),
    ]
